from common_tp3 import *

print("PASO 4 - Correlacion de fase entre los mapas log-polares")
f1 = leer_gris(F1_PATH)
f5 = leer_gris(F5_PATH)
_, _, _, _, M1log = preparar_fft(f1)
_, _, _, _, M5log = preparar_fft(f5)
LP1, centro, radio_maximo, nang, nrad = a_logpolar(M1log)
LP5, _, _, _, _ = a_logpolar(M5log)
shift, error, phasediff = phase_cross_correlation(LP1, LP5, upsample_factor=10)
print("Formula conceptual: R = FFT(A) conj(FFT(B)) / |FFT(A) conj(FFT(B))|")
print("Luego se aplica IFFT2(R) y aparece un pico de correlacion.")
print(f"Desplazamiento angular detectado: {shift[0]:.3f}")
print(f"Desplazamiento log-radial detectado: {shift[1]:.3f}")
print(f"Error informado: {error:.6f}")
corr = correlacion_fase_manual(LP1, LP5)
pico = np.unravel_index(np.argmax(corr), corr.shape)
print(f"Pico del mapa manual: fila={pico[0]}, columna={pico[1]}")
guardar_img(corr, "Mapa de correlacion de fase en log-polar", "06_mapa_correlacion_fase.png", aspect="auto", axis_off=False, mark=pico)
