from common_tp3 import *
import numpy as np

print("PIPELINE COMPLETO - Punto 3")
f1 = leer_gris(F1_PATH)
f5 = leer_gris(F5_PATH)
guardar_par(f1, f5, "f1", "f5", "01_imagenes_originales.png")
prep1, ventana, F1, M1, M1log = preparar_fft(f1)
prep5, _, F5, M5, M5log = preparar_fft(f5)
guardar_par(M1log, M5log, "log(1 + |FFT2(f1)|)", "log(1 + |FFT2(f5)|)", "04_magnitudes_fft_log.png")
LP1, centro, radio_maximo, nang, nrad = a_logpolar(M1log)
LP5, _, _, _, _ = a_logpolar(M5log)
guardar_par(LP1, LP5, "Log-polar f1", "Log-polar f5", "05_mapas_logpolares.png", aspect="auto", axis_off=False)
shift, error, phasediff = phase_cross_correlation(LP1, LP5, upsample_factor=10)
corr = correlacion_fase_manual(LP1, LP5)
pico = np.unravel_index(np.argmax(corr), corr.shape)
guardar_img(corr, "Correlacion de fase log-polar", "06_mapa_correlacion_fase.png", aspect="auto", axis_off=False, mark=pico)
delta_rho = float(shift[1])
k_log = nrad / np.log(radio_maximo)
factor = np.exp(delta_rho / k_log)
print("RESULTADO FINAL")
print(f"Desplazamiento angular: {float(shift[0]):.3f}")
print(f"Desplazamiento log-radial: {delta_rho:.3f}")
print(f"Factor de escala estimado: {factor:.6f}")
print(f"Factor inverso para compensar: {1/factor:.6f}")
